### ISSUE TITLE
Chybí tam čínština :

### ISSUE THREAD

**Issue by Kikibedna** [karelsafr/Marianska_public#2]

**Comment by karelsafr** [comment]
ok, i will add it!

**Comment by karelsafr2** [comment]
pridano a vyreseno

**Comment by Kikibedna** [comment]
děkuji

**Comment by karelsafr** [comment]
Díky moc vám všem za účast :) nezapomeňte na inovační týden -čtvrtek 9. listopadu - Od Hry k Simulaci: Python a Pygame Workshop - ([https://kalendar.vse.cz/event/show?date=4878&period=202311&selection=2](https://kalendar.vse.cz/event/show?date=4878&period=202311&selection=2&web=www.vse.cz))

Příště na viděnou!
