### ISSUE TITLE
Chybí španělština

### ISSUE THREAD

**Issue by bringback7school** [karelsafr/Marianska_public#5]
Klient zuří, že nemáme přidanou španělštinu

**Comment by karelsafr** [comment]
Díky moc vám všem za účast :) nezapomeňte na inovační týden -čtvrtek 9. listopadu - Od Hry k Simulaci: Python a Pygame Workshop - ([https://kalendar.vse.cz/event/show?date=4878&period=202311&selection=2](https://kalendar.vse.cz/event/show?date=4878&period=202311&selection=2&web=www.vse.cz))

Příště na viděnou!
