### ISSUE TITLE
chybi slovensky pozdrav

### ISSUE THREAD

**Issue by hfluskova** [karelsafr/Marianska_public#6]
prosim pridej pozdrav ve slovenstine

**Comment by karelsafr** [comment]
Díky moc vám všem za účast :) nezapomeňte na inovační týden -čtvrtek 9. listopadu - Od Hry k Simulaci: Python a Pygame Workshop - ([https://kalendar.vse.cz/event/show?date=4878&period=202311&selection=2](https://kalendar.vse.cz/event/show?date=4878&period=202311&selection=2&web=www.vse.cz))

Příště na viděnou!
