### ISSUE TITLE
přidej fibonacciho posloupnost

### ISSUE THREAD

**Issue by saltylubik** [karelsafr/Marianska_public#9]
fibonacci <- function(n) {
    if (n == 0) {
        return(0)
    } else if (n == 1) {
        return(1)
    } else {
        fib <- numeric(n)
        fib[1] <- 0
        fib[2] <- 1
        for (i in 3:n) {
            fib[i] <- fib[i-1] + fib[i-2]
        }
        return(fib)
    }
}

**Comment by karelsafr** [comment]
Díky moc vám všem za účast :) nezapomeňte na inovační týden -čtvrtek 9. listopadu - Od Hry k Simulaci: Python a Pygame Workshop - ([https://kalendar.vse.cz/event/show?date=4878&period=202311&selection=2](https://kalendar.vse.cz/event/show?date=4878&period=202311&selection=2&web=www.vse.cz))

Příště na viděnou!
